import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import PrefectureCheckList from "@/components/organisms/PrefectureCheckList";
import { fetchPrefectures } from "@/lib/resas";

interface Props {
  prefectures: Prefecture[];
  populations: PopulationTransition[];
}

export default function Home({ prefectures, populations }: Props) {
  const [checkedIndexes, setCheckedIndexes] = useState<number[]>([]);

  const toggleCheckedIndexes = (prefCode: number) => {
    if (checkedIndexes.includes(prefCode)) {
      setCheckedIndexes(checkedIndexes.filter((code) => code !== prefCode));
    } else {
      setCheckedIndexes([...checkedIndexes, prefCode]);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>都道府県一覧</h2>
        <PrefectureCheckList prefectures={prefectures} />
        <PrefectureCheckList
          prefectures={prefectures}
          checkedIndexes={checkedIndexes}
          onChange={(prefCode) => toggleCheckedIndexes(prefCode)}
        />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const prefectures = await fetchPrefectures();
  return {
    props: { prefectures },
  };
}
